-- Listar tabelas
SELECT table_name FROM user_tables;

-- Estrutura
DESC TB_MOTOS;

-- Ver todos os registros
SELECT * FROM TB_MOTOS ORDER BY DATA_PROCESSAMENTO DESC;

-- Contagem total
SELECT COUNT(*) AS TOTAL_REGISTROS FROM TB_MOTOS;

-- Agrupar por dia
SELECT TRUNC(DATA_PROCESSAMENTO) AS DIA, COUNT(*) AS TOTAL_DETECCOES
FROM TB_MOTOS
GROUP BY TRUNC(DATA_PROCESSAMENTO)
ORDER BY DIA DESC;

-- Apagar tudo
DELETE FROM TB_MOTOS;
COMMIT;
